[platformio]
default_envs = CYD-2432S028
src_dir = tripwire_x_cyd

[env:CYD-2432S028]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; คอนฟิก Pin และจอสำหรับ ESP32 CYD (Cheap Yellow Display 2.8")
build_flags =
  -DUSER_SETUP_LOADED=1
  -DILI9341_2_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DTFT_BL=21
  -DTFT_BACKLIGHT_ON=HIGH
  -DSPI_FREQUENCY=55000000
  -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000

; ดึง Library ที่ต้องใช้งานอัตโนมัติ
lib_deps =
  https://github.com/Bodmer/TFT_eSPI.git
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  https://github.com/blackhack/SimpleList.git
